site_name: KGI-Bench
site_description: Knowledge Graph Integration Benchmark

use_directory_urls: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search

docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - CLI: cli.md
  - Reproduce Movie benchmark: reproduce.md
